### ISSUE TITLE
Although no influence for result, but it look like a wrong name.

### ISSUE THREAD

**Issue by aicreatbyme** [wcventure/PERIOD#1]
https://github.com/wcventure/PERIOD/blob/7636dc7cd8c97ea2fb7c13d6d068efc3872b9d03/tool/staticAnalysis/get_aliased_info.py#L152

**Comment by aicreatbyme** [comment]
I mean the 'types'.

**Comment by wcventure** [comment]
Hi, I don't quite understand what the problem is.
The name 'typ' can be changed without influence.

**Comment by aicreatbyme** [comment]
Thanks for your response, i will think about that again.
