### ISSUE TITLE
Segmentation fault during the instrumentation with 'Combine redundant instructions'

### ISSUE THREAD

**Issue by 5hadowblad3** [wcventure/PERIOD#3]
Hi, there.

There is a segmentation fault raised when instrumenting the result from SVF.

I notice that there is a modification in your code already tackling this issue. Is there any further modification for this problem?https://github.com/wcventure/PERIOD/blob/7636dc7cd8c97ea2fb7c13d6d068efc3872b9d03/tool/staticAnalysis/DBDS-INSTRU/llvm-mode/dbds-llvm-pass.so.cc#L407

**Comment by wcventure** [comment]
When you compile .bc file using LLVM + Clang, please use -O0 option
